stages:
  - check
  - mirror

check:
  stage: check
  script:
    - cargo cmd checks
    - cargo nextest run --lib --no-default-features --profile ci --cargo-profile dev --target x86_64-unknown-linux-gnu
    - cargo tarpaulin --skip-clean --lib --no-default-features --exclude-files=src/main.rs --target-dir=target/coverage --out Xml
    - cargo cmd integration
  coverage: '/^\d+.\d+% coverage/'
  artifacts:
    when: always
    reports:
      junit: target/nextest/ci/junit.xml
      coverage_report:
        coverage_format: cobertura
        path: cobertura.xml

mirror:
  stage: mirror
  variables:
    GIT_STRATEGY: clone
    GIT_DEPTH: 0
  script:
    - git checkout -B main
    - git push --mirror git@github.com:engineering-with-ai/software-rust-base.git
  only:
    - main
